version: '3'

services:
  app:
    build: .
    entrypoint: dockerize -wait tcp://host.docker.internal:5432 -timeout 40s ./.docker/entrypoint.sh
    container_name: imersao-fullcycle-3-store-backend-service-rest
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts: 
        - 'host.docker.internal:172.17.0.1'
