version: '3'

services:
  db:
    build: .docker/postgres
    container_name: imersao-fullcycle-3-postgres-db
    restart: always
    tty: true
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'

  pgadmin:
    image: dpage/pgadmin4
    container_name: imersao-fullcycle-3-postgres-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    depends_on:
      - db
    extra_hosts: 
      - 'host.docker.internal:172.17.0.1'
